runtime: php72

env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "siswanto234432"
    CLOUDSQL_DSN: "mysql:dbname=lumenapi;unix_socket=/cloudsql/pomade:asia-southeast1:apo-manajemen"

